'use client';
import "./globals.css";
import type { Metadata } from "next";
import Favicon from '/public/images/Metadata/Favicon.ico';
import { Inter } from "next/font/google";
import { Header } from "../components//Header/Header";
import { Footer } from "../components/Footer/Footer";
import { CssBaseline } from "@mui/material";
import { ToTopButton } from "@/components/ToTopButton/ToTopButton";
import { Suspense, useEffect } from "react";
import { createContext, useState } from 'react';

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Taishin",
//   description: "Generated by create next app",
//   // viewport: "width=device-width, initial-scale=1",
//   icons: [{ rel: 'icon', url: Favicon.src }],
// };

interface LanguageContextType {
  language: string;
  setLanguage: React.Dispatch<React.SetStateAction<string>>;
}

export const CurrentLanguage = createContext<LanguageContextType>({
  language: '日本語',
  setLanguage: () => {},
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [language, setLanguage] = useState<string>(() => {
    if (typeof window !== 'undefined') {
      const savedLanguage = localStorage.getItem('selectedLanguage');
      return savedLanguage || '日本語';
    } else {
      return '日本語'; // サーバーサイドで実行される場合はデフォルト値を設定する
    }
  });

  useEffect(() => {
    localStorage.setItem('selectedLanguage', language);
  }, [language]);

  return (
    <html lang="jp">
      {/* <body className={inter.className}> */}
      <body>
        <CurrentLanguage.Provider value={{ language, setLanguage }}>
          <CssBaseline />
          <Header />
          <Suspense fallback={<div>Loading...</div>}>
            {children}
          </Suspense>
          <ToTopButton />
          <Footer />
        </CurrentLanguage.Provider>
      </body>
    </html>
  );
}
